### ISSUE TITLE
Master CF stack name convention

### ISSUE THREAD

**Issue by stormit-vn** [serverless-heaven/serverless-aws-alias#127]
By the default, when we deploy the first version without alias option, the plugin creates a master CF stack name with suffix is (dev) i.e. sls-test-project-dev, also APIG is creating with dev prefix i.e. dev-sls-test-project. Is that possible to not adding suffix/prefix to APIG and Master CF stacks?

![image](https://user-images.githubusercontent.com/13762258/43672982-c8183416-97e4-11e8-889b-2981dff367a9.png)

![image](https://user-images.githubusercontent.com/13762258/43673006-3370507c-97e5-11e8-9704-07bc3ce482f2.png)

In fact, we only want to just create a master CF for the serverless with the name that we named in the serverless.yml (e.g. sls-test-project), also APIG name should the same. Adding prefix to APIG will make us confused that we will have more APIGs to be created for the same project which will never happen when using this plugin.

**Comment by stormit-vn** [comment]
@HyperBrain Do you have any idea to update the stack names?

**Comment by johnwongapi** [comment]
+1.
We can config `stackName` for CF stack in serverless. But seems cannot customize APIG name in this plugin? please correct me if i am wrong

**Comment by aleksdikanski** [comment]
Hi @stormit-vn and @johnwongapi 

I created PR #156 that would allow setting the master alias upon first deployment using `sls deploy --masterAlias <masterAliasName>`. Could you please check if this satisfies your requirements? Thanks
