### ISSUE TITLE
Question: Can you publish the latest commits?

### ISSUE THREAD

**Issue by mcjfunk** [serverless-heaven/serverless-aws-alias#174]
Hey folks, can you publish to npm? There are changes that I'd like to leverage.

Thanks!

**Comment by Enase** [comment]
bump @HyperBrain

**Comment by HyperBrain** [comment]
Hi @Enase , will do tomorrow. Please make sure that there is a label and the package.json version is correct in master so that I  can publish a new release.
Can you prepare release notes?

**Comment by Enase** [comment]
Hi @HyperBrain 
Pls merge https://github.com/serverless-heaven/serverless-aws-alias/pull/173/
Release notes you can find [here](https://github.com/serverless-heaven/serverless-aws-alias/pull/173/files#diff-04c6e90faac2675aa89e2176d2eec7d8L483-R485)

**Comment by HyperBrain** [comment]
Merged. Proceeding now :-)

**Comment by HyperBrain** [comment]
Published to NPM and created a GitHub release including the release notes.
Closing
